# Generated by Django 5.0.6 on 2024-11-13 12:36

from django.db import migrations, models
import uuid

class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_auto_20241113_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
