# Generated by Django 5.0.6 on 2024-06-16 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0004_remove_productrating_product_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=1, editable=False, max_digits=3, null=True)),
                ('one_star', models.PositiveSmallIntegerField(default=0, editable=False)),
                ('two_star', models.PositiveSmallIntegerField(default=0, editable=False)),
                ('three_star', models.PositiveSmallIntegerField(default=0, editable=False)),
                ('four_star', models.PositiveSmallIntegerField(default=0, editable=False)),
                ('five_star', models.PositiveSmallIntegerField(default=0, editable=False)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_rating', to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('rating', models.PositiveSmallIntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('product_rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review_management.productrating')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
