# Generated by Django 5.0.6 on 2024-09-28 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productrating',
            name='five_star',
        ),
        migrations.RemoveField(
            model_name='productrating',
            name='four_star',
        ),
        migrations.RemoveField(
            model_name='productrating',
            name='one_star',
        ),
        migrations.RemoveField(
            model_name='productrating',
            name='three_star',
        ),
        migrations.RemoveField(
            model_name='productrating',
            name='two_star',
        ),
        migrations.CreateModel(
            name='RatingCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.PositiveSmallIntegerField()),
                ('count', models.PositiveSmallIntegerField(default=0)),
                ('product_rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review_management.productrating')),
            ],
        ),
    ]
