# Generated by Django 5.0.6 on 2024-11-13 12:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_management', '0003_delete_ratingcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrating',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
