# Generated by Django 5.0.6 on 2024-11-13 12:34

from django.db import migrations
import uuid


def gen_uuid0(apps, schema_editor):
    MyModel = apps.get_model("review_management", "ProductRating")
    for row in MyModel.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])

def gen_uuid1(apps, schema_editor):
    MyModel = apps.get_model("review_management", "Review")
    for row in MyModel.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])

class Migration(migrations.Migration):

    dependencies = [
        ('review_management', '0004_productrating_uuid_review_uuid'),
    ]

    operations = [
        migrations.RunPython(gen_uuid0, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(gen_uuid1, reverse_code=migrations.RunPython.noop),
    ]
