# Generated by Django 5.0.6 on 2024-06-30 10:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='stripe_token',
        ),
        migrations.AddField(
            model_name='card',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='payment_method',
            field=models.CharField(default='paypal', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='status',
            field=models.CharField(default='success', max_length=50),
            preserve_default=False,
        ),
    ]
