# Generated by Django 5.0.6 on 2024-07-08 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_management', '0002_remove_card_stripe_token_card_amount_card_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Card',
        ),
    ]
