# Generated by Django 5.0.6 on 2024-06-16 12:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long', models.DecimalField(decimal_places=6, editable=False, max_digits=9)),
                ('lat', models.DecimalField(decimal_places=6, editable=False, max_digits=9)),
                ('first_name', models.CharField(max_length=225)),
                ('last_name', models.CharField(max_length=225)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('address', models.CharField(max_length=225)),
                ('city', models.CharField(max_length=225)),
                ('country', models.CharField(max_length=225)),
                ('telephone', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(regex='^(05)\\d{9}$')])),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart_management.cart')),
            ],
        ),
    ]
