# Generated by Django 5.0.6 on 2024-07-11 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_management', '0002_remove_cart_shipping'),
        ('order_management', '0004_parcel_alter_billingaddress_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='label_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='parcel',
            name='cart',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='cart_management.cart'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parcel',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='order_management.order'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Shipment',
        ),
    ]
