# Generated by Django 5.0.6 on 2024-07-17 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0005_order_label_url_order_shipment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='label_url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
