# Generated by Django 5.0.6 on 2024-07-20 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0006_alter_order_label_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='state',
            field=models.CharField(default='Dallas', max_length=225),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Parcel',
        ),
    ]
