# Generated by Django 5.0.6 on 2024-11-13 12:34

from django.db import migrations
import uuid


def gen_uuid0(apps, schema_editor):
    MyModel = apps.get_model("order_management", "BillingAddress")
    for row in MyModel.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])

def gen_uuid1(apps, schema_editor):
    MyModel = apps.get_model("order_management", "Order")
    for row in MyModel.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])

def gen_uuid2(apps, schema_editor):
    MyModel = apps.get_model("order_management", "Shipment")
    for row in MyModel.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])

class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0009_billingaddress_uuid_order_uuid_shipment_uuid'),
    ]

    operations = [
        migrations.RunPython(gen_uuid0, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(gen_uuid1, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(gen_uuid2, reverse_code=migrations.RunPython.noop),
    ]
