# Generated by Django 5.0.6 on 2024-06-16 11:10

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('quantity', models.PositiveBigIntegerField(default=0)),
                ('shipping', models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('count_of_deals', models.PositiveBigIntegerField(db_index=True, default=0, editable=False)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='MultipleProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='shop/gallery_images/%y%m%d')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long', models.DecimalField(decimal_places=6, editable=False, max_digits=9)),
                ('lat', models.DecimalField(decimal_places=6, editable=False, max_digits=9)),
                ('first_name', models.CharField(max_length=225)),
                ('last_name', models.CharField(max_length=225)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('address', models.CharField(max_length=225)),
                ('city', models.CharField(max_length=225)),
                ('country', models.CharField(max_length=225)),
                ('telephone', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(regex='^(05)\\d{9}$')])),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=225, null=True)),
                ('size', models.CharField(max_length=225, null=True)),
                ('qty', models.PositiveBigIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('description', models.TextField()),
                ('details', models.TextField()),
                ('brand', models.CharField(max_length=225, null=True)),
                ('image', models.ImageField(upload_to='shop/images/%y%m%d')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('discount', models.PositiveSmallIntegerField(default=0)),
                ('color', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=225, null=True), size=None)),
                ('size', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=225, null=True), size=None)),
                ('in_stock', models.PositiveSmallIntegerField(default=1)),
                ('count_of_selled', models.PositiveSmallIntegerField(db_index=True, default=0, editable=False)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-time_created', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=1, editable=False, max_digits=3, null=True)),
                ('one_star', models.PositiveSmallIntegerField(default=0, editable=False)),
                ('two_star', models.PositiveSmallIntegerField(default=0, editable=False)),
                ('three_star', models.PositiveSmallIntegerField(default=0, editable=False)),
                ('four_star', models.PositiveSmallIntegerField(default=0, editable=False)),
                ('five_star', models.PositiveSmallIntegerField(default=0, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('rating', models.PositiveSmallIntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
