# Generated by Django 5.0.6 on 2024-06-16 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_management', '0001_initial'),
        ('shop', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='cart',
        ),
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart_management.cart'),
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='OrderProduct',
        ),
    ]
