# Generated by Django 5.0.6 on 2024-07-17 09:11

import django.contrib.postgres.fields
import django.db.models.deletion
import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_product_color_remove_product_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('black', 'black'), ('white', 'white'), ('blue', 'blue')], default='black', max_length=225), default=shop.models.default_colors, size=None),
        ),
        migrations.CreateModel(
            name='ProductSizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=225, null=True)),
                ('length', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('width', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('height', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_sizes', to='shop.product')),
            ],
        ),
        migrations.DeleteModel(
            name='MultipleProductParameters',
        ),
    ]
