# Generated by Django 5.0.6 on 2024-07-20 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_product_color_productsizes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsizes',
            name='height',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productsizes',
            name='length',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productsizes',
            name='size',
            field=models.CharField(default=5, max_length=225),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productsizes',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productsizes',
            name='width',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=10),
            preserve_default=False,
        ),
    ]
