# Generated by Django 5.0.6 on 2024-11-13 12:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonmailinglist',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
