# Generated by Django 5.0.6 on 2024-11-13 12:34

from django.db import migrations
import uuid


def gen_uuid0(apps, schema_editor):
    MyModel = apps.get_model("notification_management", "CommonMailingList")
    for row in MyModel.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])

class Migration(migrations.Migration):

    dependencies = [
        ('notification_management', '0002_commonmailinglist_uuid'),
    ]

    operations = [
        migrations.RunPython(gen_uuid0, reverse_code=migrations.RunPython.noop),
    ]
