# Generated by Django 5.0.6 on 2024-07-11 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='shipping',
        ),
    ]
