# Generated by Django 5.0.6 on 2024-07-20 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_management', '0002_remove_cart_shipping'),
        ('shop', '0007_alter_productsizes_height_alter_productsizes_length_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderproduct',
            options={'verbose_name': 'Order Product', 'verbose_name_plural': 'Order Products'},
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.productsizes'),
        ),
    ]
