# Generated by Django 5.0.6 on 2024-07-28 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_management', '0004_cartorderproduct_wishlist_wishlistorderproduct_and_more'),
        ('shop', '0007_alter_productsizes_height_alter_productsizes_length_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorderproduct',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderproduct_set', to='cart_management.cart'),
        ),
        migrations.AlterField(
            model_name='cartorderproduct',
            name='color',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='cartorderproduct',
            name='qty',
            field=models.PositiveBigIntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='wishlistorderproduct',
            name='color',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='wishlistorderproduct',
            name='qty',
            field=models.PositiveBigIntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='wishlistorderproduct',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.productsizes'),
        ),
        migrations.AlterField(
            model_name='wishlistorderproduct',
            name='wishlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderproduct_set', to='cart_management.wishlist'),
        ),
    ]
