# Generated by Django 5.0.6 on 2024-10-13 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_management', '0005_alter_cartorderproduct_cart_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorderproduct',
            name='product',
        ),
        migrations.RemoveField(
            model_name='wishlistorderproduct',
            name='product',
        ),
    ]
