# Generated by Django 5.0.6 on 2024-10-13 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_management', '0006_remove_cartorderproduct_product_and_more'),
        ('shop', '0007_alter_productsizes_height_alter_productsizes_length_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlistorderproduct',
            name='size',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='shop.productsizes'),
            preserve_default=False,
        ),
    ]
